apiVersion: v1
kind: Secret
metadata:
  name: worker-doacoes-secret
type: Opaque
stringData:
  ConnectionStrings__DoacoesDb: "Host=postgres-doacoes;Port=5432;Database=doacoes;Username=postgres;Password=postgres"
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"
  CampanhasApi__SharedSecret: "segredo-de-desenvolvimento-substituir-por-kubernetes-secret-em-producao"
