apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: api-service-patch.yaml
    target:
      kind: Service
      name: api-campanhas-usuarios
  - path: frontend-service-patch.yaml
    target:
      kind: Service
      name: frontend
