$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-campanhas
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: postgres-campanhas
---
$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-campanhas-pvc
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: postgres-campanhas-secret
