apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: delete-postgres-campanhas.yaml
  - path: delete-postgres-doacoes.yaml
  - path: rds-connection-patch-campanhas.yaml
    target:
      kind: Secret
      name: api-campanhas-usuarios-secret
  - path: rds-connection-patch-doacoes.yaml
    target:
      kind: Secret
      name: worker-doacoes-secret
  - path: api-service-patch.yaml
    target:
      kind: Service
      name: api-campanhas-usuarios

images:
  - name: api-campanhas-usuarios
    newName: SUBSTITUIR-PELO-TERRAFORM.dkr.ecr.SUBSTITUIR-REGIAO.amazonaws.com/api-campanhas-usuarios
    newTag: SUBSTITUIR-PELA-TAG-DA-IMAGEM
  - name: worker-doacoes
    newName: SUBSTITUIR-PELO-TERRAFORM.dkr.ecr.SUBSTITUIR-REGIAO.amazonaws.com/worker-doacoes
    newTag: SUBSTITUIR-PELA-TAG-DA-IMAGEM
