apiVersion: v1
kind: Secret
metadata:
  name: api-campanhas-usuarios-secret
type: Opaque
stringData:
  ConnectionStrings__CampanhasDb: "SUBSTITUIDO-PELO-TERRAFORM: Host=<rds-endpoint-output-do-terraform>;Port=5432;Database=campanhas;Username=<usuario>;Password=<senha-do-secrets-manager>"
