apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-campanhas
  labels:
    app: postgres-campanhas
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres-campanhas
  template:
    metadata:
      labels:
        app: postgres-campanhas
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-campanhas-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-campanhas-pvc
