apiVersion: v1
kind: ConfigMap
metadata:
  name: api-campanhas-usuarios-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "ConexaoSolidaria"
  Jwt__Audience: "ConexaoSolidaria"
  Jwt__ExpiracaoMinutos: "60"
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__Fila: "doacao-recebida"
