apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-campanhas-usuarios
  labels:
    app: api-campanhas-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-campanhas-usuarios
  template:
    metadata:
      labels:
        app: api-campanhas-usuarios
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command:
            - sh
            - -c
            - until pg_isready -h postgres-campanhas -p 5432; do echo waiting for postgres-campanhas; sleep 2; done
      containers:
        - name: api-campanhas-usuarios
          image: api-campanhas-usuarios:local
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-campanhas-usuarios-config
            - secretRef:
                name: api-campanhas-usuarios-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
