apiVersion: v1
kind: Secret
metadata:
  name: api-campanhas-usuarios-secret
type: Opaque
stringData:
  ConnectionStrings__CampanhasDb: "Host=postgres-campanhas;Port=5432;Database=campanhas;Username=postgres;Password=postgres"
  Jwt__Key: "chave-secreta-de-desenvolvimento-com-pelo-menos-32-caracteres"
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"
  Internal__SharedSecret: "segredo-de-desenvolvimento-substituir-por-kubernetes-secret-em-producao"
